### ISSUE TITLE
Z-index clarification

### ISSUE THREAD

**Issue by monkbroc** [bevacqua/css#10]
You mention twice "Keep z-index levels in variables in a single file". Could you clarify with an example? I don't understand what this rule is trying to say.

Thanks for the detailed guidelines.

**Comment by bevacqua** [comment]
Suppose you're using Stylus, 

```
z-questionmark = 10
z-dropdowns = 100
z-dialogs = 10000
```

```
.qmark
  z-index q-questionmark
```

_(etc)_

The purpose is to know at a glance what's the depth of z-indexes, which we often just set to `100000`-like values for no reason other than "this should be high enough

**Comment by monkbroc** [comment]
Thanks. The sentence was unclear because of the 2 "in". Maybe:  keep all z-index definitions in a single file and make each z-index level a variable.

**Comment by bevacqua** [comment]
Feel free to PR clarifying
