### ISSUE TITLE
btn-red is almost never a good class name

### ISSUE THREAD

**Issue by bcullman** [bevacqua/css#9]
Under the section entitled "Styles", I believe you were trying to point out how to avoid the use of !important, which is reasonable. however, I think using "btn-red" as a style name under a subheading of "Good" may also give the impression that the class name is a good one. 

It is preferable to describe the semantic meaning of the button is red (warning? error?) rather than the color, so it can be later altered by the designer (can we make it orange?) without causing a semantic disconect

**Comment by bevacqua** [comment]
Feel free to submit a PR to clarify

**Comment by flyingfisch** [comment]
Submitted a PR which should fix this issue.
